#!/bin/tcsh -f

if ("$argv" == "") echo "Usage: scatter [-logx] [-logy] [-png] [-x11] [-tty]" '"'"'plot title'"'" < XY'

set cmd = `echo $argv | sed \
	    -e 's/-logx/ set logscale x; /' \
	    -e 's/-logy/ set logscale y; /' \
	    -e 's/-x11/  set term x11; /' \
	    -e 's/-pdf/  set term pdf; set out "x.pdf"; /' \
	    -e 's/-png/  set term png size 1024,1024; set out "x.png"; /' \
	    -e 's/-tty/  set term dumb size 130, 60; set autoscale; /' \
	    -e "s/'[^']*'/ set title &; /" \
`
gnuplot -p -e "unset key; set grid; $cmd ; plot '-' u 1:2 w p pt 7 ps 0.3"

#"set terminal dumb size 130, 60 ; set autoscale ; unset key ; set style data p ; set grid; $1 plot '-' using 1:2 pt '#'"
